# Generated by Django 3.2 on 2022-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
    ]
