# Generated by Django 3.2 on 2022-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentity', '0002_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Phone Number'),
        ),
    ]
