# Generated by Django 3.2 on 2022-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentity', '0003_auto_20220925_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='invite code'),
        ),
    ]
